name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  build-production-image:
    name: Build and test production docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create docker production image
      run: docker build . --tag=abeja

    - name: Run docker production image
      run: docker run --detach --publish 9000:9000 abeja

    - name: Sleep for some seconds
      run: sleep 2

    - name: Fire a test request
      run: curl --head localhost:9000/
